### ISSUE TITLE
Running on the real time webcam and have eyes positions in each frame

### ISSUE THREAD

**Issue by FereshtehFeiz** [ChristineDewi/Blinks-Detection#1]
Hello, 

Thank you for this work, my questions are: 
1. How I can have a real time webcam demo of this? I want to get the result on the number of blinks. 
2. Can I have the gaze tracking? I mean in each frame I can have an output that eyes are looking at right/left or top/bottom ? 

Thank you

**Comment by ChristineDewi** [comment]
Hai, you need to modify the code by yourself.
this is the dataset
https://drive.google.com/drive/u/1/folders/1U2qlw-ViqdW1pny77aJGLUIEf0B-HKzZ

Regards,
*Christine Dewi, Ph.D.*
*E-mail : *
***@***.*** ***@***.***> *
***@***.*** ***@***.***>, *
***@***.*** ***@***.***>*

*Department of Information Management, *
*Chaoyang University of Technology*
168, Jifong East Road, Wufong Dist.,
Taichung City 41349, Taiwan (R.O.C.)

*Faculty of Information Technology *
*Satya Wacana Christian University*
JL. Diponegoro 52 – 60, Salatiga 50711
Central Java, Indonesia.
